version: 2
jobs:
  build:
    docker:
      - image: killbill/kbbuild:0.1.0

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx2048m

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "pom.xml" }}

      - run: mvn -DskipTests=true clean install dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ .Branch }}-{{ checksum "pom.xml" }}

      # Run checks
      - run: mvn clean install -Ptravis

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
